cart/urls.py
from django.urls import path

from cart.views import CartListView, AddToCartView, CartDeleteView

urlpatterns = [
    path("", CartListView.as_view(), name="cart-list"),
    path("add-to-cart/", AddToCartView.as_view(), name='add-to-cart'),
    path("delete-from-cart/<int:pk>/", CartDeleteView.as_view(), name='delete-from-cart'),

]


app_name = "cart"

device/urls.py
from django.urls import path

from device.views import DeviceListView, DeviceCategoryView, DeviceDetailView, DeviceCreateView, DeviceUpdateView, DeviceDeleteView, Index

urlpatterns = [
    path("", DeviceListView.as_view(), name="device-list"),
    path("category/<int:pk>/", DeviceCategoryView.as_view(), name="device-category"),
    path("<int:pk>/", DeviceDetailView.as_view(), name="device-detail"),
    path("create/", DeviceCreateView.as_view(), name="device-create"),
    path("update/<int:pk>/", DeviceUpdateView.as_view(), name="device-update"),
    path("delete/<int:pk>/", DeviceDeleteView.as_view(), name="device-delete"),
    path("index/", Index.as_view(), name="index"),
]


app_name = "device"

shop_config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop_config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("device/", include("device.urls", namespace="device")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("accounts/", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import UserCreateView, UserUpdateView

urlpatterns = [
    path("create/", UserCreateView.as_view(), name="user-create"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="user-update"),

]


app_name = "user"

cart/models.py
from django.db import models

from device.models import Device
from shop_config import settings


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    devices = models.ManyToManyField(Device, related_name="carts")

    class Meta:
        ordering = ["-id"]

device/models.py
import uuid

from django.db import models

from manufacturer.models import Manufacturer


class Device(models.Model):
    name = models.CharField(max_length=155)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, related_name="device")
    price = models.PositiveIntegerField()
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="device")
    tag = models.ManyToManyField("Tag", related_name="device")
    image = models.ImageField(upload_to="upload_models", null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.image:
            ext = self.image.name.split(".")[-1]
            self.image.name = f"{uuid.uuid4()}.{ext}"
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

manufacturer/models.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(max_length=199)
    country = models.CharField(max_length=155)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    def __str__(self):
        return self.username

user/forms.py
from django.contrib.auth.forms import UserCreationForm

from user.models import User


class UsersCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields

cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.decorators.http import require_POST
from django.views.generic import View
from django.urls import reverse_lazy

from cart.models import Cart
from device.models import Device


class CartListView(generic.ListView):
    model = Cart
    template_name = "shop/cart_list.html"
    context_object_name = "cart_list"

    def get_queryset(self):
        user = self.request.user
        # Перевірка, чи існує корзина для поточного користувача
        if hasattr(user, "cart"):
            return user.cart.devices.all()
        return Device.objects.none()


class AddToCartView(View):
    def post(self, request):
        device_id = request.POST.get("device_id")
        if device_id:
            device = Device.objects.get(pk=device_id)
            # Отримання або створення корзини для поточного користувача
            cart, created = Cart.objects.get_or_create(user=request.user)
            # Додавання товару до корзини
            cart.devices.add(device)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class CartDeleteView(View):
    def post(self, request, pk):
        cart = get_object_or_404(Cart, user=request.user)
        device = get_object_or_404(Device, pk=pk)
        cart.devices.remove(device)
        return redirect("cart:cart-list")

device/views.py
from django.urls import reverse_lazy
from django.views import generic

from device.models import Device, Category


class DeviceListView(generic.ListView):
    model = Device
    template_name = "shop/device_list.html"


def get_category_list():          # TODO тег 16 відео seldefu також мейт
    return Category.objects.all()


class DeviceCategoryView(generic.ListView):
    model = Device
    template_name = "shop/category_detail.html"
    context_object_name = "devices"

    def get_queryset(self):
        category_id = self.kwargs["pk"]
        return Device.objects.filter(category_id=category_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.get(pk=self.kwargs["pk"])
        return context


class DeviceDetailView(generic.DetailView):
    model = Device
    template_name = "shop/device_detail.html"


class DeviceCreateView(generic.CreateView):
    model = Device
    fields = "__all__"
    template_name = "shop/device_form.html"
    success_url = reverse_lazy("device:device-list")


class DeviceUpdateView(generic.UpdateView):
    model = Device
    fields = "__all__"
    template_name = "shop/device_form.html"
    success_url = reverse_lazy("device:device-list")


class DeviceDeleteView(generic.DeleteView):
    model = Device
    success_url = reverse_lazy("device:device-list")
    template_name = "shop/device_confirm_delete.html"


class Index(generic.ListView):
    pass

user/views.py
from django.urls import reverse_lazy
from django.views import generic

from user.forms import UsersCreationForm
from user.models import User


class UserCreateView(generic.CreateView):
    model = User
    form_class = UsersCreationForm
    success_url = reverse_lazy("device:device-list")
    template_name = "shop/user_form.html"


class UserUpdateView(generic.UpdateView):
    model = User
    form_class = UsersCreationForm
    success_url = reverse_lazy("device:device-list")
    template_name = "shop/user_form.html"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <meta charset="UTF-8">
  <title>Shop</title>
</head>
<body>

  {% block navbar %}
    {% include "includes/navbar.html" %}
  {% endblock %}

  {% block sidebar %}
    {% include "includes/sidebar.html" %}
  {% endblock %}


  {% block content %}{% endblock %}



</body>
</html>

templates/includes/navbar.html
{% load static %}
<div class="bg-dark mt-3 p-3">
  <ul class="sidebar-nav list-group">
    <li class="list-group-item bg-dark d-flex justify-content-between align-items-center">
      <a class="text-white" href="{% url 'device:device-list' %}">Home</a>
      <span class="text-white">
        <a href="{% url 'cart:cart-list' %}">
          <img src="{% static 'photos/cart_photo.jpg' %}" alt="Cart Photo" class="cart-photo" style="width: 1cm; height: 1cm;">
        </a>
      </span>
    </li>
    <ul>
      {% if user.is_authenticated %}
        <li>User: {{ user.username }}</li>
        <li>
          <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit">Logout!</button>
          </form>
        </li>
      {% else %}
        <li><a href="{% url 'login' %}">Login!</a></li>
      {% endif %}
    </ul>
  </ul>
</div>


{#{% if user.is_authenticated %}#}
{#        <li>User: {{ user.get_username }}</li>#}
{#        <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>#}
{#      {% else %}#}
{#        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>#}
{#      {% endif %}#}

templates/includes/sidebar.html
<div class="container-fluid">
  <div class="row">
    <div class="bg-dark">
      <div class="p-3">
        <a class="text-white" href="{% url 'device:device-list' %}">All device</a>
        {% load category_tags %}
        {% get_category as categories %}

        {% for category in categories %}
          <p><a class="text-white" href="{% url 'device:device-category' pk=category.id %}">{{ category.name }}</a></p>
        {% endfor %}
      </div>
    </div>
    <div class="col-9">
    </div>
  </div>
</div>

templates/shop/cart_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    {% if cart_list %}
      {% for device in cart_list %}
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            {% if device.image %}
              <img src="{{ device.image.url }}" class="card-img-top" alt="{{ device.name }}" style="width: 100%; height: auto;">
            {% else %}
              <img src="{% static 'photos/no_photo.png' %}" alt="no_photo" class="no_photo" style="width: 100%; height: auto;">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ device.name }}</h5>
              <p class="card-text">Price: {{ device.price }}</p>
              <form action="{% url 'cart:delete-from-cart' pk=device.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Remove from Cart</button>
              </form>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:3 and not forloop.last %}
          </div><div class="row justify-content-center">
        {% endif %}
      {% endfor %}
    {% else %}
      <h4>Your cart is empty</h4>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/shop/category_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    {% for device in devices %}
  <div class="col-md-4 mb-4">
    <a href="{% url 'device:device-detail' pk=device.id %}" style="text-decoration: none;">
      <div class="card h-100">
        {% if device.image %}
          <img src="{{ device.image.url }}" class="card-img-top" alt="{{ device.name }}" style="width: 100%; height: auto;">
        {% else %}
          <img src="{% static 'photos/no_photo.png' %}" alt="no_photo" class="no_photo" style="width: 100%; height: auto;">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ device.name }}</h5>
          <p class="card-text">Price: {{ device.price }}</p>
          <form action="{% url 'cart:add-to-cart' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="device_id" value="{{ device.id }}">
            <button type="submit" class="btn btn-primary">Add to Cart</button>
          </form>
        </div>
      </div>
    </a>
  </div>
  {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div><div class="row justify-content-center">
  {% endif %}
{% endfor %}

  </div>
</div>

{% endblock %}



{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{##}
{#<div class="container">#}
{#  <div class="row justify-content-center">#}
{#    {% for device in devices %}#}
{#      <div class="col-md-4 mb-4">#}
{#        <div class="card h-100">#}
{#          <div class="card-body">#}
{#            <h5 class="card-title">{{ device.name }}</h5>#}
{#            {% if device.image %}#}
{#              <img src="{{ device.image.url }}" class="card-img-top" alt="{{ device.name }}" style="width: 100%; height: auto;">#}
{#            {% endif %}#}
{#            <p class="card-text">Price: {{ device.price }}</p>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    {% endfor %}#}
{#  </div>#}
{#</div>#}
{##}
{#{% endblock %}#}

templates/shop/device_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete device {{ device.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>

{% endblock %}

templates/shop/device_detail.html
{% extends "base.html" %}

{% block content %}

  <h5>{{ device.name }}</h5>
  <h5>{{ device.price }}</h5>
  {% if device.image %}
    <img src="{{ device.image.url }}" class="card-img-top" alt="{{ device.name }}" style="width: 100%; height: auto;">
  {% endif %}

{% endblock %}

templates/shop/device_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<h1>{{ object|yesno:"Update,Create" }} Device</h1>
  <form action="" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/shop/device_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<p><a href="{% url 'device:device-create' %}">Create Device</a></p>
<p><a href="{% url 'user:user-create' %}">Create User</a></p>
<p><a href="{% url 'user:user-update' pk=user.id %}">Update User</a></p>

<div class="container">
  <div class="row justify-content-center">
    {% for device in device_list %}
  <div class="col-md-4 mb-4">
    <a href="{% url 'device:device-detail' pk=device.id %}" style="text-decoration: none;">
      <div class="card h-100">
        {% if device.image %}
          <img src="{{ device.image.url }}" class="card-img-top" alt="{{ device.name }}" style="width: 100%; height: auto;">
        {% else %}
          <img src="{% static 'photos/no_photo.png' %}" alt="no_photo" class="no_photo" style="width: 100%; height: auto;">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ device.name }}</h5>
          <p class="card-text">Price: {{ device.price }}</p>
          <a href="{% url 'device:device-update' pk=device.id %}">Update</a>
          <p><a href="{% url 'device:device-delete' pk=device.id %}">Delete</a></p>
          <form action="{% url 'cart:add-to-cart' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="device_id" value="{{ device.id }}">
            <button type="submit" class="btn btn-primary">Add to Cart</button>
          </form>
        </div>
      </div>
    </a>
  </div>
  {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div><div class="row justify-content-center">
  {% endif %}
{% endfor %}

  </div>
</div>

{% endblock %}

templates/shop/index.html
{% extends "base.html" %}

{% block content %}

  <h1>Shop</h1>
  <a href="{% url 'user:user-create' %}">Create account</a>

{% endblock %}

templates/shop/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<h1>{{ object|yesno:"Update,Create" }} User</h1>
  <form action="" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}